import { useEffect, useState } from 'react'
import { useUserStore } from '../../stores/useUserStore'
import { useAppStore } from '../../stores/useAppStore'
import { setSettings as saveSettingsToDB } from '../../lib/db'
import { generateUserInitials } from '../../utils/user-initials'

interface EditProfileModalProps {
  isOpen: boolean
  onClose: () => void
}

export const EditProfileModal = ({ isOpen, onClose }: EditProfileModalProps) => {
  const { user, updateProfile, isLoading } = useUserStore()
  const settings = useAppStore((s) => s.settings)
  const setSettingsStore = useAppStore((s) => s.setSettings)
  const [name, setName] = useState(user?.name || '')
  const [initials, setInitials] = useState(user?.initials || '')
  const [error, setError] = useState('')
  const [preferredEvalView, setPreferredEvalView] = useState<'objectives' | 'questions'>(
    settings.evaluationViewMode || 'objectives'
  )
  const [preferredObjView, setPreferredObjView] = useState<'objectives' | 'questions'>(
    settings.objectivesViewMode || 'objectives'
  )

  useEffect(() => {
    if (!isOpen || !user) return
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setName(user.name)
     
    setInitials(user.initials)
     
    setPreferredEvalView(settings.evaluationViewMode || 'objectives')
     
    setPreferredObjView(settings.objectivesViewMode || 'objectives')
    setError('')
  }, [isOpen, user, settings.evaluationViewMode, settings.objectivesViewMode])

  const handleSubmit = async () => {
    if (!name.trim()) {
      setError('Le nom ne peut pas être vide')
      return
    }
    if (!initials.trim()) {
      setError('Le trigramme ne peut pas être vide')
      return
    }

    try {
      setError('')
      await updateProfile(name.trim(), initials.trim())
      // Save view preferences to settings (store + SQLite)
      const next = { ...settings, evaluationViewMode: preferredEvalView, objectivesViewMode: preferredObjView }
      setSettingsStore(next)
      saveSettingsToDB(next)
      onClose()
    } catch (err) {
      setError('Erreur lors de la modification du profil')
      console.error(err)
    }
  }

  const handleClose = () => {
    setName(user?.name || '')
    setInitials(user?.initials || '')
    setError('')
    onClose()
  }

  const autoGeneratedInitials = generateUserInitials(name)

  if (!isOpen || !user) return null

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4" role="dialog" aria-modal="true">
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full">
        {/* Header */}
        <div className="bg-linear-to-r from-blue-600 to-blue-700 px-6 py-8 text-white">
          <h2 className="text-2xl font-bold">Modifier le profil</h2>
          <p className="text-blue-100 text-sm mt-2">
            Triplet actuel : <span className="font-semibold">{user.initials}</span>
          </p>
        </div>

        {/* Body */}
        <div className="p-6">
          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm font-medium">
              {error}
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">
                Nom complet
              </label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Ex: Marie Arthur Dupont"
                className="w-full border border-slate-300 rounded-lg px-3 py-2 text-slate-900 placeholder-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all"
                autoFocus
              />
              <p className="text-xs text-slate-500 mt-1">
                Le trigramme est généré automatiquement (1ère lettre de chaque mot + dernière lettre du dernier mot)
              </p>
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">
                Trigramme <span className="text-xs text-slate-500 font-normal">(max 3 lettres)</span>
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={initials}
                  onChange={(e) => setInitials(e.target.value.toUpperCase().slice(0, 3))}
                  placeholder="Ex: MAT"
                  maxLength={3}
                  className="flex-1 border border-slate-300 rounded-lg px-3 py-2 text-slate-900 placeholder-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all font-semibold"
                />
                {autoGeneratedInitials && autoGeneratedInitials !== initials && (
                  <button
                    onClick={() => setInitials(autoGeneratedInitials)}
                    className="px-3 py-2 bg-slate-100 text-slate-600 font-sm text-xs font-medium rounded-lg hover:bg-slate-200 transition-all whitespace-nowrap"
                    title={`Utiliser le trigramme généré : ${autoGeneratedInitials}`}
                  >
                    Utiliser {autoGeneratedInitials}
                  </button>
                )}
              </div>
              {autoGeneratedInitials && (
                <p className="text-xs text-slate-500 mt-1">
                  Trigramme généré : <span className="font-semibold text-slate-700">{autoGeneratedInitials}</span>
                </p>
              )}
            </div>

            <div className="pt-4 border-t border-slate-100">
              <h3 className="text-sm font-bold text-slate-800 mb-3">Préférences d'affichage</h3>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
                    Onglet Évaluation
                  </label>
                  <div className="flex bg-slate-100 p-1 rounded-lg">
                    <button
                      type="button"
                      onClick={() => setPreferredEvalView('objectives')}
                      className={`flex-1 text-xs font-semibold py-2 rounded-md transition-all ${
                        preferredEvalView === 'objectives'
                          ? 'bg-white text-slate-800 shadow-sm'
                          : 'text-slate-500 hover:text-slate-700'
                      }`}
                    >
                      Vue par Objectifs
                    </button>
                    <button
                      type="button"
                      onClick={() => setPreferredEvalView('questions')}
                      className={`flex-1 text-xs font-semibold py-2 rounded-md transition-all ${
                        preferredEvalView === 'questions'
                          ? 'bg-white text-slate-800 shadow-sm'
                          : 'text-slate-500 hover:text-slate-700'
                      }`}
                    >
                      Vue par Questions
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
                    Onglet Objectifs
                  </label>
                  <div className="flex bg-slate-100 p-1 rounded-lg">
                    <button
                      type="button"
                      onClick={() => setPreferredObjView('objectives')}
                      className={`flex-1 text-xs font-semibold py-2 rounded-md transition-all ${
                        preferredObjView === 'objectives'
                          ? 'bg-white text-slate-800 shadow-sm'
                          : 'text-slate-500 hover:text-slate-700'
                      }`}
                    >
                      Vue par Objectifs
                    </button>
                    <button
                      type="button"
                      onClick={() => setPreferredObjView('questions')}
                      className={`flex-1 text-xs font-semibold py-2 rounded-md transition-all ${
                        preferredObjView === 'questions'
                          ? 'bg-white text-slate-800 shadow-sm'
                          : 'text-slate-500 hover:text-slate-700'
                      }`}
                    >
                      Vue par Questions
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Preview */}
          <div className="mt-6 p-4 bg-slate-50 rounded-lg border border-slate-200">
            <p className="text-xs font-semibold text-slate-500 uppercase mb-3">
              Aperçu du nouveau profil
            </p>
            <div className="flex items-center gap-3">
              <div
                className="w-12 h-12 rounded-full flex items-center justify-center text-white font-bold text-sm"
                style={{ backgroundColor: user.color }}
              >
                {initials || autoGeneratedInitials || '—'}
              </div>
              <div>
                <div className="font-semibold text-slate-900 text-sm">{name || 'Votre nom'}</div>
                <div className="text-xs text-slate-500 mt-1">
                  Trigramme :{' '}
                  <span className="font-bold text-slate-700">
                    {initials || autoGeneratedInitials || '—'}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex gap-3 px-6 py-4 bg-slate-50 border-t border-slate-200 rounded-b-2xl">
          <button
            onClick={handleClose}
            className="flex-1 px-4 py-2 bg-white border border-slate-300 text-slate-700 text-sm font-semibold rounded-lg hover:bg-slate-50 transition-all"
            disabled={isLoading}
          >
            Annuler
          </button>
          <button
            onClick={handleSubmit}
            className="flex-1 px-4 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 shadow-sm transition-all disabled:opacity-50"
            disabled={isLoading}
          >
            {isLoading ? 'Modification...' : 'Modifier'}
          </button>
        </div>
      </div>
    </div>
  )
}
